### ISSUE TITLE
Tm can not be computed

### ISSUE THREAD

**Issue by k1197445** [matdoering/openPrimeR#1]
Hi, I followed the tutorial trying to compute the Tm of primers, but failed. Could you have a look at the reason? Many thanks

> constraint.df = check_constraints(primer.df, template.df, settings, active.constraints = "melting_temp_range")
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input
In addition: Warning message:
executing %dopar% sequentially: no parallel backend registered 
Warning messages:
1: In call.melt.single(out.primers[seq.idx[[i]]], out.complements[seq.idx[[i]]],  :
  MELTING could not compute the Tm:
File: /tmp/RtmpMIHvTh/melt_seqs_1b7d69d6c4dc346a04f0544b03a6093ea6cf555175893.txt.results.csv
Error in read.table(file = file, header = header, sep = sep, quote = quote, : no lines available in input

2: In min(c(Tm.fw$Tm_C_fw[x], Tm.rev$Tm_C_rev[x]), na.rm = TRUE) :
  no non-missing arguments to min; returning Inf
3: In min(c(Tm.fw$Tm_C_fw[x], Tm.rev$Tm_C_rev[x]), na.rm = TRUE) :
  no non-missing arguments to min; returning Inf

**Comment by k1197445** [comment]
To add, I used R3.6.

**Comment by matdoering** [comment]
Which version of MELTING is installed on your system? 

Works for me with version 5.1

You can check the version via:

> melting -V

Can you open the file that is located in /tmp/? What are the contents?

**Comment by k1197445** [comment]
Thanks. Problem solved.
