### ISSUE TITLE
Long running time of the phase 3

### ISSUE THREAD

**Issue by obenno** [matdoering/openPrimeR#12]
Hi,

Thanks a lot for the amazing tool!

I wasing using openPrimeR to design multiplex primers for mouse TRB templates, and the phase 3 took days and is still running, while it works fine for the human TRB templates. Is there any way to invoke multiple threads for this step? 

Thank you in advance!
ob

messages for R console:
```
-> Available number of candidates after relaxation: 5231 (97.56% coverage)
# Phase 3: Optimization of primers
Computing cross dimers. This may take a while ...
 Dimerization info: 
	o DeltaG cutoff: -5
	o Number of pairs: 27363361
	o Number of dimers: 9235302 (33.75%)
	o Number of dimerizing primers: 5225
Determining melting temperature sets:
Melting temperature set @ 58.17 with 705 primers (95.12% coverage)
	o Computing optimization constraints for target coverage 100%
```

openPrimeR script:

```
#! /usr/local/bin/Rscript

library(openPrimeR)
library(dplyr)
library(stringr)

args <- commandArgs(trailingOnly = TRUE)

template_fasta <- args[1]
leader_fasta <- args[2]
settings.xml <- args[3]

parallel_setup(cores = NULL)

## load template
hdr.structure <- c("ACCESSION", "GROUP", "SPECIES", "FUNCTION")
seq.df <- read_templates(template_fasta, hdr.structure, delim = "|", id.column = "GROUP")
seq.df$Group <- seq.df$Group %>%
    str_replace("-.*" , "") %>%
    str_replace("S.*",  "") %>%
    str_replace("\\*\\d+$", "")
## add leader region
template.df <- assign_binding_regions(seq.df, fw = leader_fasta, rev = NULL)

## load settings
design.settings <- read_settings(settings.xml)

optimal.primers <- design_primers(template.df, mode.directionality = "fw",
                                  settings = design.settings,
                                  required.cvg = 1,
                                  max.degen = 1,
                                  opti.algo = "ILP")

write_primers(optimal.primers$opti, "opr_designed_primers.fa")
```

Inputs:

[templates_settings.zip](https://github.com/matdoering/openPrimeR/files/10821157/templates_settings.zip)

running env:

```
docker run --rm -it -u 999 -v $(pwd):/data -w /data mdoering88/openprimer:latest bash
```

**Comment by matdoering** [comment]
Thanks for the positive feedback!

The optimization is always the challenging part and will always be prohibitively slow for larger data sets. Some general tips that may work as a quick fix:

- Change the `opti.algo` from `ILP` to `Greedy`
- Consider removing the cross dimerization constraint: computing the dimerization matrix can be challenging (in your case it worked)
- Consider more stringent filtering settings before starting the optimization. For example, in your case, 100% coverage with the given constraints wasn't possible, so setting it to a smaller percentage, e.g. 90% should yield a smaller primer pool.

A more specific tip based on your inputs
- Adjust/investigate the algorithm: it seems you're stuck somewhere [here](https://github.com/matdoering/openPrimeR/blob/b1c9ff79ab032c132d6a07b48252b5057d652dcc/R/optimization_algo.R#L1131), which is a part of the code that evaluates the constraints again. Based on the size of the data, I wouldn't anticipate that it should take that long. In the worst case, it could be a stuck while loop. While the package was developed to provide a generally applicable primer design routine, that's actually something that is not so easily achieved, so I'd encourage you to consider implementing your own primer design function utilizing the building blocks of the package.

I hope some of these tips help to alleviate the problem for you!

**Comment by obenno** [comment]
Thank you so much for the response!

Yes, I think the while loop will never stop when the coverage constrains cannot be fulfilled. Since the relax function adjusts primer sets only via `$melting_temp_diff`, I relaxed the "Melting temperature deviation" limits from 0 ~ 3 to 0 ~ 6, and the target coverage was kept to 1. This indead solved the issue and get me the results. Hope this information will be helpful to anyone encountering the same issue.

```
constraintLimits(settings)[["melting_temp_diff"]] <- c("min"=0, "max"=6)
```
