### ISSUE TITLE
Docker image does not have Melting, ViennaRNA, or OligoArraryAux

### ISSUE THREAD

**Issue by ymjzhang** [matdoering/openPrimeR#13]
Dear authors, 
After pulling the docker image in Docker Desktop and loading the package in R, it says the environment does not have Melting, ViennaRNA, or OligoArraryAux. Could you check out your image and update things if needed? 
Below is what I did after running the image in Docker Desktop:

> $ R
> 
> R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
> Copyright (C) 2020 The R Foundation for Statistical Computing
> Platform: x86_64-pc-linux-gnu (64-bit)
> 
> R is free software and comes with ABSOLUTELY NO WARRANTY.
> You are welcome to redistribute it under certain conditions.
> Type 'license()' or 'licence()' for distribution details.
> 
> R is a collaborative project with many contributors.
> Type 'contributors()' for more information and
> 'citation()' on how to cite R or R packages in publications.
> 
> Type 'demo()' for some demos, 'help()' for on-line help, or
> 'help.start()' for an HTML browser interface to help.
> Type 'q()' to quit R.
> 
> \> library(openPrimeR)
> 
> Melting not available
> ViennaRNA not available
> OligoArrayAux not available
> There are missing/non-functioning external tools.
> To use the full potential of openPrimeR, please make sure
> that the required versions of the speciied tools are
>  
>  installed and that they are functional:
> o MELTING (http://www.ebi.ac.uk/biomodels/tools/melting/)
> o ViennaRNA (http://www.tbi.univie.ac.at/RNA/)
> o OligoArrayAux (http://unafold.rna.albany.edu/OligoArrayAux.php)
> o MAFFT (http://mafft.cbrc.jp/alignment/software/)
> The number of cores for was set to '2' by 'parallel_setup()'.
> \>

**Comment by matdoering** [comment]
Hi there,
I don't have any issues on Arch Linux:

```
docker pull mdoering88/openprimer
docker run -it --rm mdoering88/openprimer:latest bash
```

```
[~]$ R

R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(openPrimeR)
The number of cores for was set to '2' by 'parallel_setup()'.
> 
```

Are you using docker correctly?
