### ISSUE TITLE
Error: stack file is corrupt

### ISSUE THREAD

**Issue by cz0430** [matdoering/openPrimeR#14]
Hi,
I tried to use openprimer and installed all external tools,
when I run the script in conda env under centOS system, I got the below error msg:

> library(openPrimeR)
Error: stack file is corrupt
Error: stack file is corrupt
There are missing/non-functioning external tools.
To use the full potential of openPrimeR, please make sure
that the required versions of the speciied tools are
 
                installed and that they are functional:
o MELTING (http://www.ebi.ac.uk/biomodels/tools/melting/)
o OligoArrayAux (http://unafold.rna.albany.edu/OligoArrayAux.php)
o Pandoc (http://pandoc.org)
The number of cores for was set to '2' by 'parallel_setup()'.
Warning messages:
1: In check.tool.function() :
  oligoArrayAux failed checks: disabled. Do you have the UNAFOLDDAT environment variable set?
2: In check.tool.function() :
  oligoArrayAux failed checks: disabled. Do you have the UNAFOLDDAT environment variable set?
3: In fun(libname, pkgname) :
  'Pandoc' is non-functional, since 'pdflatex' is not installed on your system.

How can I fix such problems?Thanks a lot!

**Comment by matdoering** [comment]
Maybe have a look here? https://support.bioconductor.org/p/9139543/

**Comment by cz0430** [comment]
Thanks a lot for reply. I have solved the above issue by reinstalling oligoarrayaux. However, when I ran the script provided on the HTML link get from bioconductor. I got the following error at the create_report step:

> create_report(constraint.df, template.df, my.file, 
+               settings, sample.name = "My analysis")

kpathsea: Running mktexfmt pdftex.fmt
Can't locate mktexlsr.pl in @INC (@INC contains: /public/home/miniconda3/envs/openprimer2/share/texlive/tlpkg /public/home/miniconda3/envs/openprimer2/share/texlive/texmf-dist/scripts/texlive /public/home/miniconda3/envs/openprimer2/lib/perl5/5.32/site_perl /public/home/miniconda3/envs/openprimer2/lib/perl5/site_perl /public/home/miniconda3/envs/openprimer2/lib/perl5/5.32/vendor_perl /public/home/miniconda3/envs/openprimer2/lib/perl5/vendor_perl /public/home/miniconda3/envs/openprimer2/lib/perl5/5.32/core_perl /public/home/miniconda3/envs/openprimer2/lib/perl5/core_perl .) at /public/home/miniconda3/envs/openprimer2/bin/mktexfmt line 23.
BEGIN failed--compilation aborted at /public/home/miniconda3/envs/openprimer2/bin/mktexfmt line 25.
!!! Error: pdfTeX run failed with value 1!

kpathsea: Running mktexfmt pdftex.fmt
Can't locate mktexlsr.pl in @INC (@INC contains: /public/home/miniconda3/envs/openprimer2/share/texlive/tlpkg /public/home/miniconda3/envs/openprimer2/share/texlive/texmf-dist/scripts/texlive /public/home/miniconda3/envs/openprimer2/lib/perl5/5.32/site_perl /public/home/miniconda3/envs/openprimer2/lib/perl5/site_perl /public/home/miniconda3/envs/openprimer2/lib/perl5/5.32/vendor_perl /public/home/miniconda3/envs/openprimer2/lib/perl5/vendor_perl /public/home/miniconda3/envs/openprimer2/lib/perl5/5.32/core_perl /public/home/miniconda3/envs/openprimer2/lib/perl5/core_perl .) at /public/home/miniconda3/envs/openprimer2/bin/mktexfmt line 23.
BEGIN failed--compilation aborted at /public/home/miniconda3/envs/openprimer2/bin/mktexfmt line 25.
!!! Error: pdfTeX run failed with value 1!

kpathsea: Running mktexfmt pdftex.fmt
Can't locate mktexlsr.pl in @INC (@INC contains: /public/home/miniconda3/envs/openprimer2/share/texlive/tlpkg /public/home/miniconda3/envs/openprimer2/share/texlive/texmf-dist/scripts/texlive /public/home/miniconda3/envs/openprimer2/lib/perl5/5.32/site_perl /public/home/miniconda3/envs/openprimer2/lib/perl5/site_perl /public/home/miniconda3/envs/openprimer2/lib/perl5/5.32/vendor_perl /public/home/miniconda3/envs/openprimer2/lib/perl5/vendor_perl /public/home/miniconda3/envs/openprimer2/lib/perl5/5.32/core_perl /public/home/miniconda3/envs/openprimer2/lib/perl5/core_perl .) at /public/home/miniconda3/envs/openprimer2/bin/mktexfmt line 23.
BEGIN failed--compilation aborted at /public/home/miniconda3/envs/openprimer2/bin/mktexfmt line 25.
!!! Error: pdfTeX run failed with value 1!
[WARNING] Deprecated: --self-contained. use --embed-resources --standalone
tlmgr: package repository https://ctan.math.illinois.edu/systems/texlive/tlnet (verified)
[1/1, ??:??/??:??] install: wallpaper [2k]
running mktexlsr ...
done running mktexlsr.
tlmgr: package log updated: /public/home/.TinyTeX/texmf-var/web2c/tlmgr.log
tlmgr: command log updated: /public/home/.TinyTeX/texmf-var/web2c/tlmgr-commands.log
tlmgr: package repository https://ctan.math.illinois.edu/systems/texlive/tlnet (verified)
[1/1, ??:??/??:??] install: eso-pic [4k]
running mktexlsr ...
done running mktexlsr.
tlmgr: package log updated: /public/home/.TinyTeX/texmf-var/web2c/tlmgr.log
tlmgr: command log updated: /public/home/.TinyTeX/texmf-var/web2c/tlmgr-commands.log
tlmgr: package repository https://ctan.math.illinois.edu/systems/texlive/tlnet (verified)
[1/1, ??:??/??:??] install: caption [60k]
running mktexlsr ...
done running mktexlsr.
tlmgr: package log updated: /public/home/.TinyTeX/texmf-var/web2c/tlmgr.log
tlmgr: command log updated: /public/home/.TinyTeX/texmf-var/web2c/tlmgr-commands.log
! LaTeX Error: Unicode character 五 (U+4E94)
               not set up for use with LaTeX.

Error : LaTeX failed to compile /tmp/RtmpTfM4HG/file31f19250ee1b1.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See file31f19250ee1b1.log for more info.外: Warning messages:
1: In matrix(c(my.ok, my.fail, ref.ok, ref.fail), nrow = 2, ncol = 2,  :
  data length differs from size of matrix: [22 != 2 x 2]
2: `guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead. 
NULL
Warning message:
In render_report(params, "report.Rmd", fname) :
  No PDF file was produced, please check the console output and whether all Latex dependencies are installed (Texlive available?).
> Rscript -e 'tinytex::install_tinytex();rmarkdown::render("QuantDataProcessingScript.Rmd")'
Error: unexpected string constant在"Rscript -e 'tinytex::install_tinytex();rmarkdown::render("QuantDataProcessingScript.Rmd")'"

It seems a pdfLatex problem, so I installed r-tinytex, the same error still showed up. May I know how i can solve it?thanks a lot!

**Comment by matdoering** [comment]
Seems you need to fix your Latex install on your machine. Since this is out-of-scope of the package, I will close this one.
