### ISSUE TITLE
Melting temp constraint removes all primers

### ISSUE THREAD

**Issue by mhallerud** [matdoering/openPrimeR#15]
I am running openPrimeR on a set of 65 sequences to develop primers for amplicon sequencing. I previously had the package up and running properly on a dummy dataset, but now that I'm running on my actual dataset I am having an issue. At Phase 2 a) in the design_primers function, I lose all of my primers at the melting_temp_range constraint. I have rerun design_primers with an extremely lax melting temperature constraint (0-100) to see if this was actually the issue, and I have also tried running on single sequences and a different set of sequences, but I am consistently getting 0 primers at this step. I also tried restarting R and reloading the package, but there's no change. I also checked my PATH variable in R and it's properly directing to the dependencies. I'm running R version 4.2.1 on Mac with MELTING 5.2.0, Oligo Array Aux 3.8.1. I'm a bit at a loss of what else to check, but I would really prefer using this package to running manually via Primer3. Help is greatly appreciated!
<img width="509" alt="image" src="https://github.com/matdoering/openPrimeR/assets/43869036/fb4bd1b8-ec9a-49ef-a1a5-036d993c44cc">

**Comment by Chessrein** [comment]
The same problem as me！
My codes are copied form tutorial. Please have a look for helping me! Thanks alot.

> fasta.file <- system.file("extdata", "IMGT_data", "templates", 
                          "Homo_sapiens_IGH_functional_exon.fasta", package = "openPrimeR")
# Load the template sequences from 'fasta.file'
hdr.structure <- c("ACCESSION", "GROUP", "SPECIES", "FUNCTION")
seq.df.simple <- read_templates(fasta.file)
seq.df <- read_templates(fasta.file, hdr.structure, delim = "|", id.column = "GROUP")

l.fasta.file <- system.file("extdata", "IMGT_data", "templates", 
                            "Homo_sapiens_IGH_functional_leader.fasta", package = "openPrimeR")
template.df <- assign_binding_regions(seq.df, fw = l.fasta.file, rev = NULL)


settings.xml <- system.file("extdata", "settings", 
                            "A_Taq_PCR_design.xml", package = "openPrimeR")
settings <- read_settings(settings.xml)


optimal.primers <- design_primers(template.df[1:2,], mode.directionality = "fw",
                                  settings = settings)



![image](https://github.com/matdoering/openPrimeR/assets/58138749/cb55dc60-9cb6-4c21-8bd7-1e7d0cd83719)

**Comment by Chessrein** [comment]
But the same code can run in my pc's openprimer without the packages 'MELTING ', 'ViennaRNA ','OligoArrayAux ', 'MAFFT ' and 'Pandoc '. That is confuse me alot.

![image](https://github.com/matdoering/openPrimeR/assets/58138749/cd8812dc-af03-42c8-a8c5-d83d0f4452f3)

**Comment by tppf** [comment]
uninstall MELTING 5.2.0

**Comment by matdoering** [comment]
The package has been developed with MELTING 5.1.1. So, it may be that there are issues with newer versions.
If you remove MELTING, the melting temperature calculations will default to the rule of thumb (less accurate than MELTING).
