### ISSUE TITLE
Could not find function "adjust. rev. allocated. regions"

### ISSUE THREAD

**Issue by tppf** [matdoering/openPrimeR#16]
Thank you for developing the software. It's great. But I found a small issue when using the latest Docker image. When I upload the sequence file, selecting Uniform in the Definition of allowed binding region will result in an error. The software will remain at the position shown in Figure 3. Warning: Error in adjust. rev. allocated. regions: could not find function "adjust. rev. allocated. regions". If you have time, please help me, thank you.
![图片1](https://github.com/matdoering/openPrimeR/assets/60166694/f9c9dea3-0a4e-4815-9a75-be4c1f731b11)
![图片2](https://github.com/matdoering/openPrimeR/assets/60166694/5380616a-b383-49e2-81f1-7bc4e619d07e)
![图片3](https://github.com/matdoering/openPrimeR/assets/60166694/c8469f85-2198-449a-a84c-218eeb7f0e56)
![图片4](https://github.com/matdoering/openPrimeR/assets/60166694/9b8bc5c0-13ed-4085-9b3b-db4b0520aeb9)

**Comment by ksamuk** [comment]
Also having this problem.

**Comment by matdoering** [comment]
The UI-based version has been deprecated. Please use the  `openPrimeR` R library instead.
