### ISSUE TITLE
Please define the UNAFOLDDAT variable in your path before using OligoArrayAux.

### ISSUE THREAD

**Issue by jxshi** [matdoering/openPrimeR#2]
Hi,

I tried to use ```openPrimeR``` package on my machine. I have already set ```UNAFOLDDAT``` path in ```~/.bashrc``` file by adding this line ```export UNAFOLDDAT=/home/jshi/biosoft/oligoarrayaux-3.8/data```, but error message popped up as listed follow. 

```
> settings <- read_settings(settings.xml)
Reading settings file: C_Taq_PCR_high_stringency.xml
Due to missing external tools the following constraints were ignored:cross_dimerization,self_dimerization
Due to missing external tools the following coverage constraints were ignored:coverage_model
Warning message:
In check.tool.function() :
  Please define the UNAFOLDDAT variable in your path before using OligoArrayAux.
```
I typed ```echo $UNAFOLDDAT``` command and it returned:
```
/home/jshi/biosoft/oligoarrayaux-3.8/data
```

Can you check for me please?

Thank you and best wishes!

Jianxiang

**Comment by jxshi** [comment]
I solved the problem by add ```:$PATH``` to the end of the last line.
```export UNAFOLDDAT=/home/jshi/biosoft/oligoarrayaux-3.8/data:$PATH``` worked.
Will check out how the package works tomorrow. 
Thank you and cheers!

Jianxiang

**Comment by warthmann** [comment]
Not sure why and how the above works. I suggest to set the variables for openPrimeR (the PATH variable as well as UNAFOLDDAT)  in the respective R-script like so:

old_path <- Sys.getenv("PATH")
new_path <- old_path
new_path <- paste(new_path, "/Library/TeX/texbin", sep = ":")
new_path <- paste(new_path, "/Users/xy/miniconda3/envs/openprimer/bin/", sep = ":")
new_path <- paste(new_path, "/Users/xy/Applications/MELTING5.2.0/executable", sep = ":")
new_path <- paste(new_path, "/Users/xy/miniconda3/envs/openprimer/share/oligoarrayaux", sep = ":")
Sys.setenv(PATH = new_path)
Sys.setenv(UNAFOLDDAT = "/Users/xy/miniconda3/envs/openprimer/share/oligoarrayaux")
