### ISSUE TITLE
can not assign rev binding region correctly with provided fasta sequence

### ISSUE THREAD

**Issue by k1197445** [matdoering/openPrimeR#3]
Hi I try to design both forward and reverse primers. With provided fasta sequence to assign binding region, fw binding region was resolved properly, but rev binding regions not.

below is the code I used:
template = read_templates("MSI_template.fa", hdr.structure = "GROUP", id.column = "GROUP", delim = ">")
template = assign_binding_regions(template, fw = "fw.bs.fa", rev = "rev.bs.fa")

FASTA sequence of template, binding regions are attached

[fw.bs.fa.TXT](https://github.com/matdoering/openPrimeR/files/4234104/fw.bs.fa.TXT)
[MSI_template.fa.TXT](https://github.com/matdoering/openPrimeR/files/4234105/MSI_template.fa.TXT)
[rev.bs.fa.TXT](https://github.com/matdoering/openPrimeR/files/4234112/rev.bs.fa.TXT)

**Comment by k1197445** [comment]
In many cases, the position of rev binding regions were assigned even upstream of fw binding regions.

**Comment by matdoering** [comment]
Thanks for finding this bug and the files for recreating it. I've just commited a change that should fix the issue: https://github.com/matdoering/openPrimeR/commit/5e4ef9e96265ac2df024986e4ffda1d6cf48d9a7

You should be able to get it working with the latest openPrimeR version on GitHub.
