### ISSUE TITLE
conda recipe incomplete

### ISSUE THREAD

**Issue by nick-youngblut** [matdoering/openPrimeR#7]
The bioconda recipe for [openprimer](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bioconductor-openprimer/meta.yaml) states:

> `# SystemRequirements: MAFFT (>= 7.305), OligoArrayAux (>= 3.8), ViennaRNA (>= 2.4.1), MELTING (>= 5.1.1), Pandoc (>= 1.12.3)`

...but doesn't actually install them, so the recipe is incomplete. It appears that all of this software is available via conda, so why not include them in the openprimer recipe? That would help identify any potential dependency conflicts via CI.

**Comment by matdoering** [comment]
The conda recipe is not part of openPrimeR but maintained by the conda community, so please contact the authors of the conda recipe.
