### ISSUE TITLE
Instructions for installing dependencies on Windows are required.

### ISSUE THREAD

**Issue by Leytoncito** [matdoering/openPrimeR#9]
Hi, 

Using docker and a web page is nice, but it seems limiting, I tried to use this library in Rstudio and when I run library(openprimeR), it throws me this:

There are missing/non-functioning external tools.
To use the full potential of openPrimeR, please make sure
that the required versions of the speciied tools are
 
                installed and that they are functional:
o MELTING (http://www.ebi.ac.uk/biomodels/tools/melting/)
o ViennaRNA (http://www.tbi.univie.ac.at/RNA/)
o OligoArrayAux (http://unafold.rna.albany.edu/OligoArrayAux.php)
o MAFFT (http://mafft.cbrc.jp/alignment/software/)
o Pandoc (http://pandoc.org)
Warning in fun(libname, pkgname) :
  'Pandoc' is non-functional, since 'pdflatex' is not installed on your system.

So, I try to install these dependencies, for windows (in .exe or .msi formats)... and even when I install everything I still get this message, so I consider it unclear how to install the dependencies and it greatly limits the use of this tool .

I realize there is a way to couple docker with R, however this seems dedicated to Linux.

Is there any way to solve that?

Thanks in advance.

**Comment by matdoering** [comment]
Either figure it out on Windows and share your setup, so it can be added to the docs or just use docker/Unix/mac. You can also use just the R library using the docker image, as documented here: https://hub.docker.com/r/mdoering88/openprimer/
